name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build devcontainer, test and build debians
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/schanzerracing/arwo_advanced_ros2_concepts
          imageName: ghcr.io/schanzerracing/arwo_advanced_ros2_concepts
          imageTag: ${{ github.ref_name }}
          push: always
          runCmd: >
            /bin/bash -c
            ". /opt/ros/humble/setup.bash
            && colcon build
            && colcon test --return-code-on-test-failure
            && .devcontainer/build_debs.sh"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: src/*.deb
