name: CI/CD

on: push

jobs:
  checkout:
    name: Build and test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build devcontainer, test and build debians
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/schanzerracing/arwo_advanced_ros2_concepts
          cacheFrom: ghcr.io/schanzerracing/arwo_advanced_ros2_concepts
          push: never
          runCmd: >
            /bin/bash -c
            ". /opt/ros/humble/setup.bash
            && colcon build
            && colcon test --return-code-on-test-failure
            && .devcontainer/build_debs.sh"
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: src/*.deb
