name: CI
on: push
jobs:
  checkout:
    name: Build and test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/schanzerracing/arwo_advanced_ros2_concepts
          cacheFrom: ghcr.io/schanzerracing/arwo_advanced_ros2_concepts
          push: never
          runCmd: >
            /bin/bash -c
            ". /opt/ros/humble/setup.bash
            && colcon build
            && colcon test --return-code-on-test-failure
            && colcon test-result --verbose
            && .devcontainer/build_debs.sh"
      - name: Upload debians
        uses: actions/upload-artifact@v4
        with:
          path: src/*.deb
